main.py --do_valid --do_test --data_path data/nell-q2b -n 1 -b 1000 -d 1000 -lr 0.1 --disable_warmup --max_steps 1000 --cpu_num 0 --geo cqd --valid_steps 20 --tasks 2i --print_on_screen --test_batch_size 1 --optimizer Adagrad --reg_weight 0.05 --log_steps 5 --checkpoint_path models/nell-q2b --cqd d2 --cqd-t-norm prod --cqd-normalize --cqd-k 2 --no-save --cuda
overwritting args.save_path
logging to models/nell-q2b
Traceback (most recent call last):
  File "main.py", line 508, in <module>
    main(parse_args())
  File "main.py", line 261, in main
    with open('%s/stats.txt'%args.data_path) as f:
FileNotFoundError: [Errno 2] No such file or directory: 'data/nell-q2b/stats.txt'
